language: node_js
node_js:
  - 6
  - 8
  - 10.12.0
deploy:
  - provider: script
    script: ./node_modules/.bin/nlm release
    skip_cleanup: true
    'on':
      branch: master
      node: 10.12.0
before_install:
  - npm i -g npm@^6
